### ISSUE TITLE
variable descriptions 

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#106]
Jack, what are these variables?

threshold_public_goods.1.player.oConA 
threshold_public_goods.1.player.oConB 
threshold_public_goods.1.player.yConA 
threshold_public_goods.1.player.yConB 
threshold_public_goods.1.player.yRem 
threshold_public_goods.1.player.yPay 
threshold_public_goods.1.player.payOutB

**Comment by mcdaij** [comment]
Those are for calculating the quiz amounts so that it always works out with the same answers (except for the last question) regardless of what the thresholds and payouts are. In short:
threshold_public_goods.1.player.oConA : other "person's" contribution to A
threshold_public_goods.1.player.oConB : other "person's" contribution to B
threshold_public_goods.1.player.yConA : your contribution to A
threshold_public_goods.1.player.yConB : your contribution to B
threshold_public_goods.1.player.yRem : your Remaining tokens (unallocated)
threshold_public_goods.1.player.yPay : total payout (payOutB +yRem) 
threshold_public_goods.1.player.payOutB : how much B payed out (A will never pay out, unless the thresholds are weird)
