### ISSUE TITLE
Points decimal issue

### ISSUE THREAD

**Issue by mcdaij** [billuraksoy/virtual_lab#107]
By default in oTree, points are stored as integers with no fractional component. Multiplying them by .3 in the last part means that they will have a decimal component more often than not, but then if you try to save a decimal to the payoff at the end it will round (sometimes down), so a player could end up in a situation like this:
![image](https://user-images.githubusercontent.com/68068255/95776454-625db900-0c92-11eb-8401-2a9358642525.png)
OTree does have a way of dealing with this, we can set the number of decimal places for the tokens currency to 2, then it will allow a decimal component in the payoff. However, this means that whenever tokens are printed they'll be printed as "1.00 tokens".

The way I see it there are a few options:
1.) Keep points as integers and round up to the nearest whole dollar amount at the end (and change the  desc to tell the player)
2.) Give tokens 2 decimal places and have them print as "1.00" everywhere they're shown
or, if you have a problem with them printing like that:
3.) Give tokens 2 decimal places and change the way they're printed through Django everywhere they're shown

If time's an issue, the first 2 would take all of 30 seconds, the third one would take ~15 minutes to find all the references.

**Comment by billuraksoy** [comment]
I sent an email regarding this but typing here for good bookkeeping reasons:
It looks like the ideal  solution is the third method you mentioned. I would like to make sure that subjects see the correct earnings and also the correct amounts are recorded. At the same time, I do not want to see two decimals anywhere else (e.g., instructions, contributions page, round summary page etc.)

So I would like to proceed with the third option even though it is more time costly. But, I am worried about mistakes happening in this process since you will have to make so many edits to the code. All in all, please go with the third option but also take longer than 15 min if needed. After you are done with the edits and once they pass your tests, can you please let me know?

**Comment by billuraksoy** [comment]
@mcdaij I see two decimals on contribution screens and summary pages. 
![Screen Shot 2020-10-12 at 5 57 00 PM](https://user-images.githubusercontent.com/44884690/95794713-8e8b3100-0cb6-11eb-961e-faebe861378a.png)

![Screen Shot 2020-10-12 at 5 57 36 PM](https://user-images.githubusercontent.com/44884690/95794714-90ed8b00-0cb6-11eb-9b1e-82aa7aaeced2.png)

**Comment by mcdaij** [comment]
Whoops, forgot a push, sorry!

**Comment by billuraksoy** [comment]
@mcdaij I just tested it again and I am still getting the same problem. Although it may be because of the branch conflict? 

Another issue is with the decision entry box. The decision entry box should not have 0.00. It may deceive people into thinking that they can contribute in decimals. Previously, it was just 0 and that was fine.

**Comment by mcdaij** [comment]
The database needed to be reset, it works on the Heroku testing branch now. (I also have a download of the database from testing that I got before resetting it if you need that for anything).
