### ISSUE TITLE
sequential treatments: group member's contribution

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#113]
(NOTE: I made several text edits on a testing branch and then recently merged them. Please make sure this went through successfully before you make edits. Please work on the testing branch)

There is a bug on the contribution screen for sequential game.  

When the subject enters a contribution amount that is higher than 5, the warning pops up, but also "group member's contribution" part gets increases. Say the group member contributed 2 tokens. I, as the second mover, tried to contribute 7 tokens. The error message appears on top. But at the same time, "group member's contribution" becomes 9 (7+2).

I have not tested what happens if I add wrong amounts into both group accounts (say trying to contribute 6 to A and 7 to B).

<img width="1021" alt="Screen Shot 2020-10-13 at 10 20 32 PM" src="https://user-images.githubusercontent.com/44884690/95937113-09327a00-0da5-11eb-816d-fb8487778143.png">
<img width="1007" alt="Screen Shot 2020-10-13 at 10 20 36 PM" src="https://user-images.githubusercontent.com/44884690/95937115-09cb1080-0da5-11eb-8f6d-604d74462266.png">

**Comment by billuraksoy** [comment]
When working on this, please test it carefully. Since we are running the experiment on Thursday, I wont have time to do a thorough testing, I will trust that you tested, checked the data and everything works.

**Comment by mcdaij** [comment]
I'll take a look at this first thing after my exam tomorrow morning, I should be able to start working around 9. I'll be very careful.

**Comment by mcdaij** [comment]
Okay, so after double checking the code I can say for the record that this bug is entirely visual so there's nothing to worry about on the data end.

I'll be a bit extra thorough with this to make sure you're convinced this is a safe change:

What was happening was: the group contribution numbers were being calculated in the same manner as on the results page: by the sum of all contributions from all players (including yourself). These variables were just being sent to the page for display and weren't saved anywhere, because the group contribution would need to be recalculated on the results page anyway. The input results were being tagged as invalid on the page level, meaning you couldn't submit with them invalid, but that didn't stop the page from displaying them anyway.

The fix for this was a super simple one line addition to the function for calculating the sum of the group contributions. It will now check before adding, for every in the current player's group, that the player input it's adding does not belong to the current player. Or simply: it will only add _everyone else's_ contribution to the display variable.

**Comment by billuraksoy** [comment]
Thanks very much Jack! This makes and sounds good. I tested it and it looks fine. By the way, this was not an issue for the practice round, correct? Or did you fix it for that too?

**Comment by mcdaij** [comment]
It was using a separate system entirely, but I did make a minor change to make sure that it saved properly because I noticed a minor issue while testing.
