### ISSUE TITLE
H13 errors

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#120]
In heroku (under events for Web dyno), I  see a few H13 errors during the sessions. Can you please investigate this and make sure that this is not impacting the data? 

https://devcenter.heroku.com/articles/error-codes#h13-connection-closed-without-response

**Comment by billuraksoy** [comment]
Also, looking at throughput, I see a few 5XX error codes. What are these?
https://devcenter.heroku.com/articles/metrics#throughput

**Comment by mcdaij** [comment]
A few questions:
How many users did you have connecting to the site?
Over how much time did they connect?

**Comment by billuraksoy** [comment]
I had 38 people and they were connected for about 45-50 min. 

But I am seeing these errors in my last two sessions today as well (even after I increased the dyno type to 2X for web and upgraded redis). I had about 30 people in today's sessions. They did not seem to have any issues during the sessions but I again see H13 errors (which occurs during the contributions game but mostly during SVO).

In these screenshots below, the most recent spikes are from the morning session with 30 people (plus 2x dyno and upgraded redis). The previous spikes are from the session yesterday that pretty crashed at the end. 

![Screen Shot 2020-10-21 at 2 33 40 PM](https://user-images.githubusercontent.com/44884690/96807927-c21c3880-13e5-11eb-80ed-d4b9a4477a2d.png)

![Screen Shot 2020-10-21 at 2 33 54 PM](https://user-images.githubusercontent.com/44884690/96807889-aadd4b00-13e5-11eb-8f48-a65cb4877da1.png)

**Comment by mcdaij** [comment]
H13s are 5XX errors, specifically 503 errors. 5XX errors are errors that are the fault of the server and 4XX errors, such as 404:page not found, are the fault of the user. After doing extensive testing, here are some probable causes for the errors, and their potential remedies if necessary.

Whenever someone tries to join a full session it will give a 404 error. (No fix necessary, this is intended.)
H13s can occur if someone closes the page during the game and we execute a timeout on them. (Also intended)
Some of the H13s may have happened because the server topped out its memory or max connections and had to throttle the refreshes.

Ultimately, I don't think there's much to be worried about, upgrading the dynos should have solved the problem already, but this is definitely worth keeping an eye on going forward.
