### ISSUE TITLE
groupBThresholdMet and groupAThresholdMet

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#56]
**groupBThresholdMet** and **groupAThresholdMet** variables are only recorded in the end app which is confusing since they do not play the game in this app. We should have these variables recorded in the end app. Instead, They should be recorded in all rounds in the actual game app. 

Similarly, **groupATotalContribution** and **groupBTotalContribution** variables are recorded in the end app and this is confusing. They are already being recorded as acc_a_total and acc_b_total in all rounds. Thus we should not record groupATotalContribution and groupBTotalContribution in the end app.

**Comment by mcdaij** [comment]
Those variables in the end app are for recording the randomly chosen payment round info like you asked in #54. I didn't record weather the threshold was met in every round because I assumed you didn't want me to clutter the data table with extra rows, especially when the code to do so would only require settings you put in at the beginning and data that's already saved in the table (acc_a_total & acc_b_total), if you'd prefer to have a boolean recorded every round for that though it'd be super quick to implement, just let me know.

**Comment by billuraksoy** [comment]
This explanation was helpful for those variables. Please keep a note of this which will be helpful when you create a codebook ( a short description of each variable that is being recorded, as mentioned in #31 ). You can also start doing this as you work on the code if that is easier. It is up to you since I do not need it urgently. 

Please have the code record whether or not the threshold was met in each round for each group account. This should be coded using the variables so that the data would be correct even when I change the threshold levels for some treatments later. Thank you.
