### ISSUE TITLE
 security vulnerability issue

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#62]
What is this? What are the potential concerns with this? We may have to fix this issue. 

![Screen Shot 2020-09-01 at 12 44 26 PM](https://user-images.githubusercontent.com/44884690/91882487-08a8ae80-ec51-11ea-9aa3-81acdb2799b3.png)

**Comment by mcdaij** [comment]
oTree explicitly requires Django 2.2.12, however all the update to .13 does is fix the two security issues present, so it should be compatible. I just pushed a revision to the requirements and although oTree whines about it being the "wrong version" in the console it still works and only installs .13. This issue shouldn't have effected testing, and because the pilot wasn't a public release I wouldn't be too worried about it.
