### ISSUE TITLE
pull request and a question

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#63]
I did a quick test of the code and it seemed like it works at first glance. Great job, thank you! I will do a more thorough testing in the following hours and open new issues if needed. 

A couple of things:
1. I had made changes to the master branch last weekend and it looks like the testing branch you worked on did not have the most updated copy of the master branch. Can you please merge the testing branch with the master so that I can see the final version of the code?

2. I see that there are two gmaes (mptgT0 and mptgT1). I used T0 and changed the session config to simultaneous=0 to test. What is the difference between T0 and T1? Is T0

**Comment by mcdaij** [comment]
1)
Sure thing, I haven't been pulling up from master into testing because generally I don't expect changes to be made directly to master, and testing's the only other branch. There was a bit of a merge conflict because of this, where I had to template out some text in the warning page in order to allow it to display correctly for both the sequential and simultaneous treatments on the testing branch, but you'd made text edits to that section on master. It was a simple fix though, not a huge issue, testing has been merged and I'll be sure to pull from master more frequently in the future.
2) 
T0 is simultaneous by default with the large difference treatment applied
T1 is simultaneous by default with the small difference treatment applied
(you can still edit any of the variables once you select a treatment, and I'd be happy to provide other treatments with simultaneous not selected etc.)
