### ISSUE TITLE
session.config.total_rounds variable 

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#70]
When I was creating a session, I set this variable to 5, but I still had to play for 10 rounds.

**Comment by billuraksoy** [comment]
Here is an example data set that shows this issue:
[All apps - wide-2020-09-13 (1).xlsx](https://github.com/billuraksoy/virtual_lab/files/5214738/All.apps.-.wide-2020-09-13.1.xlsx)

**Comment by mcdaij** [comment]
I hadn't implemented this because I've been trying to find a workaround that isn't the solution I just pushed. oTree really doesn't like variable round numbers, I put in some code to let you enter any round number less than or equal to 10 (if you go less than 1 it will default to 10) the problem is, no matter what maximum amount of rounds you put in, if you set the number of rounds less at runtime then you'll have several empty columns at the end where the rest of the data would go, which is why I didn't give you more wiggle room on the far end yet. The 10 is coded to a constant in threshold_public_goods_game/pages.py so it's an easy change if you decide you want a different upper limit.

**Comment by billuraksoy** [comment]
I will leave this open for future reference and remove the milestone.
