### ISSUE TITLE
threshold_public_goods_game.10.group.id_in_subsession is wrong when a subject times out

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#72]
I noticed that when a subject times out, this variable gets a little messed up. The code pretends as if the timed-out subject and their partner are still in the game.  Thus, it assigns them to groups.  When subjects are matched with a timed-out subject (or their partner who also left the game and moved to the survey), the data recording for other variables also get messed up ( player.acc_a_total, player.acc_b_total, thresh_a_met, thresh_b_met, payoff(?) - I am not 100% sure about the payoff variable).

The funny is that this does not create any issues from subjects' perspective. The game continues with no issues. But the data is not being recorded correctly. 

I am attaching a sample data set for you to observe this issue. Check out the highlighted parts. While I was testing, I kept track of who was in which group. Thus you will also my markings next to the "group.id_in_subsession" variables in each round 
[All apps - wide-2020-09-13.xlsx](https://github.com/billuraksoy/virtual_lab/files/5214727/All.apps.-.wide-2020-09-13.xlsx)
which indicates who was partnered with whom.

**Comment by mcdaij** [comment]
Good catch, this was actually to do with otree's implementation; they make all the player objects for all of the subsessions before anything happens and when a player switches app or round they actually just take over control of the player object that was there waiting for them, the problem is that oTree doesn't notice if a participant isn't inhabiting that player object, or in fact if a participant won't *ever* inhabit that player object, and so when you request the viable players from the subsession it automatically gives you *every* player object, not just the active ones. I wrote a workaround that just groups the dropped out players with one another.

**Comment by billuraksoy** [comment]
I tested it with 6 subjects, 1 timed out, and the code worked. thank you.
