### ISSUE TITLE
mtpgg_practice/Start missing text

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#88]
It reads
"Remember, you will **have seconds** to submit your decisions." 

The duration variable is missing. Please update the seconds variable on this page.

**Comment by billuraksoy** [comment]
I actually ended up fixing this in text myself. Now it says "Remember, you will have {**duration variable**} seconds to submit your decisions."
So it looks like there was a misunderstanding here since you also issued a fix which did not fix what I wanted. What is it that you fixed with this code change? @mcdaij

**Comment by mcdaij** [comment]
So the edit for that came in 2 parts, the change to the pages.py file that pushes the data in so the html can access it, and the html file that actually changes how the page looks. From the push files it looks like the pages.py update went through but not the html change. I'm not sure why I wouldn't have pushed the html change, or where it went since then, because I'm sure I double checked to make sure that it was working before I pushed.
