### ISSUE TITLE
Summary page to be updated 

### ISSUE THREAD

**Issue by billuraksoy** [billuraksoy/virtual_lab#97]
Since now the subjects are being paid also according to their earnings in the SVO game, we need to incorporate this. 

1. We need to record all of their allocation choices, earnings, svo related measures (as calculated in the svo code). 

2. We also need to update our summary page and backend calculations. Please update the summary as:

**Earnings Summary:**
     Participation Payment: $ X
     Part 1 Earnings: $ X
     Part 2 Earnings: $ X
     Total Earnings: $ X (_sum of all three above_)

**PART 1 Earnings:** 

     Round chosen for payment: X
     Tokens Earned in this round: X
     Part 1 Earnings:  $ X

**PART 2 Earnings:**
      Decision Chosen for Payment: (_out of 15 decisions, one of them will be randomly chosen for payment and displayed here. this needs to be recorded in data)_ 
     As a Receiver, you received X tokens (1 token = $0.30) 
     As a Sender, you kept X tokens (1 token = $0.30) 
     Part 2 Earnings :   $ X (_basically the sum of receiver and sender tokens multiplied by 0.30_)

**Comment by billuraksoy** [comment]
@mcdaij The currency conversation rate for SVO task was updated to be 0.30. Can you please make that edit for all treatments? 
I think it needs to be changed in three place:
1. Task 2 intro page where we mention the conversation rate
2. Summary page text
3. calculation of earnings from Part 2.

**Comment by billuraksoy** [comment]
@mcdaij  I just realized that In the simultaneous small diff treatment, we have the correct conversation rate for Task 2 (0.30) on PArt 2 Instructions page. But this is incorrect in the sequential treatment. Why is that? The text on this page should not be conditional on treatment.

**Comment by mcdaij** [comment]
It shouldn't be conditional on anything, it's hardcoded because I wasn't expecting it to change. I can't replicate that locally or on the heroku so it was almost certainly just cached by your browser (since it's basically just a pure html page) and not updated properly.

It's now updated everywhere, but just a note, the Part2.html page in svo isn't included in the pages.py file so it won't ever be called up. It appeared to just have a few additions to the text on the already existing Intro.html page, but didn't appear to actually be a new page, so at the time I just added the text changes to the (already implemented) Intro.html page. I didn't want to just up and delete because I wasn't sure what you had in mind for it, but I think that might be causing some of the confusion.
